sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in multi-k8s-265408-0b2dd14e94d0.json.enc -out multi-k8s-265408-0b2dd14e94d0.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth active-service-account --key-file service-account.json
